// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import {IProofVerifier} from "../interfaces/IProofVerifier.sol";

/// @title UltraHonkVerifier — On-chain verification of ZAseon's Noir/UltraHonk proofs
/// @notice Verifies proofs generated by ZAseon's 21 Noir circuits using the UltraHonk
///         proving system. UltraHonk proofs are natively EVM-verifiable with moderate
///         gas cost (~400K gas per verification).
/// @dev This is a reference implementation. In production, deploy the auto-generated
///      UltraHonk verifier contract from `nargo codegen-verifier`.
contract UltraHonkVerifier is IProofVerifier {
    // ── Types ──────────────────────────────────────────────────────────

    struct HonkVerificationKey {
        uint256 circuitSize;
        uint256 numPublicInputs;
        // Commitments to circuit polynomials (KZG)
        uint256[2] qm; // Multiplication selector
        uint256[2] ql; // Left selector
        uint256[2] qr; // Right selector
        uint256[2] qo; // Output selector
        uint256[2] qc; // Constant selector
        uint256[2] q4; // Fourth selector (UltraPlonk)
        uint256[2] qArith; // Arithmetic selector
        uint256[2] qSort; // Sort/range selector
        uint256[2] qLookup; // Lookup selector
        uint256[2] sigma1; // Permutation polynomial 1
        uint256[2] sigma2; // Permutation polynomial 2
        uint256[2] sigma3; // Permutation polynomial 3
        uint256[2] sigma4; // Permutation polynomial 4
        uint256[2] id1; // Identity polynomial 1
        uint256[2] id2; // Identity polynomial 2
        uint256[2] id3; // Identity polynomial 3
        uint256[2] id4; // Identity polynomial 4
        uint256[2] table1; // Lookup table 1
        uint256[2] table2; // Lookup table 2
        uint256[2] table3; // Lookup table 3
        uint256[2] table4; // Lookup table 4
        uint256[2] lagrangeFirst;
        uint256[2] lagrangeLast;
        bool initialized;
    }

    // ── State ──────────────────────────────────────────────────────────

    /// @notice VK for each circuit type
    HonkVerificationKey public transferVK;
    HonkVerificationKey public withdrawVK;
    HonkVerificationKey public aggregationVK;

    address public governance;

    // ── Errors ─────────────────────────────────────────────────────────

    error Unauthorized();
    error VKNotInitialized();
    error VKAlreadyInitialized();
    error InvalidProof();
    error InvalidProofLength();
    error PublicInputCountMismatch();
    error PointNotOnCurve();

    modifier onlyGovernance() {
        if (msg.sender != governance) revert Unauthorized();
        _;
    }

    constructor() {
        governance = msg.sender;
    }

    // ── IProofVerifier ─────────────────────────────────────────────────

    /// @inheritdoc IProofVerifier
    function verifyTransferProof(
        bytes calldata proof,
        uint256[] calldata publicInputs
    ) external view returns (bool) {
        if (!transferVK.initialized) revert VKNotInitialized();
        return _verifyUltraHonk(proof, publicInputs, transferVK);
    }

    /// @inheritdoc IProofVerifier
    function verifyWithdrawProof(
        bytes calldata proof,
        uint256[] calldata publicInputs
    ) external view returns (bool) {
        if (!withdrawVK.initialized) revert VKNotInitialized();
        return _verifyUltraHonk(proof, publicInputs, withdrawVK);
    }

    /// @inheritdoc IProofVerifier
    function verifyAggregatedProof(
        bytes calldata proof,
        uint256[] calldata publicInputs
    ) external view returns (bool) {
        if (!aggregationVK.initialized) revert VKNotInitialized();
        return _verifyUltraHonk(proof, publicInputs, aggregationVK);
    }

    /// @inheritdoc IProofVerifier
    function provingSystem() external pure returns (string memory) {
        return "UltraHonk";
    }

    // ── VK Management ──────────────────────────────────────────────────

    function setTransferVK(
        HonkVerificationKey calldata vk
    ) external onlyGovernance {
        if (transferVK.initialized) revert VKAlreadyInitialized();
        transferVK = vk;
        transferVK.initialized = true;
    }

    function setWithdrawVK(
        HonkVerificationKey calldata vk
    ) external onlyGovernance {
        if (withdrawVK.initialized) revert VKAlreadyInitialized();
        withdrawVK = vk;
        withdrawVK.initialized = true;
    }

    function setAggregationVK(
        HonkVerificationKey calldata vk
    ) external onlyGovernance {
        if (aggregationVK.initialized) revert VKAlreadyInitialized();
        aggregationVK = vk;
        aggregationVK.initialized = true;
    }

    function setGovernance(address _governance) external onlyGovernance {
        governance = _governance;
    }

    // ── BN254 Curve Constants ──────────────────────────────────────────

    /// @dev BN254 curve order (prime field)
    uint256 private constant BN254_P =
        21888242871839275222246405745257275088696311157297823662689037894645226208583;

    /// @dev BN254 curve parameter b (y^2 = x^3 + 3)
    uint256 private constant BN254_B = 3;

    // ── Internal ───────────────────────────────────────────────────────

    /// @dev UltraHonk verification with structural validation
    /// In production, replace with the auto-generated verifier from Noir's `nargo codegen-verifier`.
    /// This implementation validates proof structure and EC points but delegates the actual
    /// pairing check to the production verifier.
    function _verifyUltraHonk(
        bytes calldata proof,
        uint256[] calldata publicInputs,
        HonkVerificationKey storage vk
    ) private view returns (bool) {
        // 1. Public input count must exactly match
        if (publicInputs.length != vk.numPublicInputs) return false;

        // 2. Minimum proof size: UltraHonk proofs contain
        //    4 wire commitments (4 x 64B) + grand product (64B) +
        //    quotient polys (4 x 64B) + opening evals + KZG proof
        //    Minimum ~ 768 bytes for valid UltraHonk
        if (proof.length < 768) return false;

        // 3. Validate proof is properly structured (multiple of 32 bytes)
        if (proof.length % 32 != 0) return false;

        // 4. Extract and validate wire commitment EC points (first 4 G1 points)
        //    Each G1 point = (x, y) = 64 bytes
        for (uint256 i = 0; i < 4; i++) {
            uint256 offset = i * 64;
            if (offset + 64 > proof.length) return false;

            uint256 px = uint256(bytes32(proof[offset:offset + 32]));
            uint256 py = uint256(bytes32(proof[offset + 32:offset + 64]));

            // Point at infinity is invalid for commitments
            if (px == 0 && py == 0) return false;

            // Validate point is on BN254 G1 curve: y^2 = x^3 + 3 (mod p)
            if (!_isOnCurveG1(px, py)) return false;
        }

        // 5. Validate all public inputs are within field
        for (uint256 i = 0; i < publicInputs.length; i++) {
            if (publicInputs[i] >= BN254_P) return false;
        }

        // 6. Production verification:
        //    In production, this delegates to the full UltraHonk verification algorithm
        //    generated by `nargo codegen-verifier`. The auto-generated contract handles:
        //    - Transcript initialization with Poseidon/Keccak
        //    - Challenge generation (beta, gamma, alpha, zeta)
        //    - Gate relation computations
        //    - Multi-scalar multiplication for batch verification
        //    - KZG pairing check via ecPairing precompile
        //
        // TESTNET ONLY: structural validation above catches malformed proofs.
        // The pairing check is NOT performed here — deploy the real verifier for mainnet.
        return true;
    }

    /// @dev Check if (x, y) is on BN254 G1: y^2 = x^3 + 3 (mod p)
    function _isOnCurveG1(uint256 x, uint256 y) private pure returns (bool) {
        if (x >= BN254_P || y >= BN254_P) return false;

        uint256 lhs = mulmod(y, y, BN254_P);
        uint256 x3 = mulmod(mulmod(x, x, BN254_P), x, BN254_P);
        uint256 rhs = addmod(x3, BN254_B, BN254_P);

        return lhs == rhs;
    }
}
