/**
 * Client-side stealth address helpers.
 *
 * Implements the ECDH-based stealth address protocol:
 *   1. Recipient publishes meta-address (spend + view public keys)
 *   2. Sender generates ephemeral keypair, computes shared secret via ECDH
 *   3. Sender derives stealth address and publishes an announcement
 *   4. Recipient scans announcements using the view tag for fast filtering
 *
 * Uses keccak256 as the hash function (matching the on-chain library).
 * In production circuits, Poseidon is used — the off-chain SDK bridges
 * between keccak (EVM) and Poseidon (ZK) where needed.
 */

import {
  type Hex,
  type Address,
  keccak256,
  encodePacked,
  getAddress,
} from "viem";
import type { StealthMetaAddress } from "./wallet";

// ── Types ─────────────────────────────────────────────

/** An ephemeral keypair generated by the sender. */
export interface EphemeralKeyPair {
  /** Private scalar (32 bytes). */
  privateKey: Hex;
  /** Compressed public key x-coordinate. */
  publicKeyX: Hex;
  /** Parity byte (27 or 28). */
  parity: number;
}

/** A stealth announcement that the sender publishes on-chain. */
export interface StealthAnnouncement {
  /** Ephemeral public key x-coordinate. */
  ephemeralPubKeyX: Hex;
  /** Ephemeral key parity. */
  ephemeralPubKeyParity: number;
  /** The derived stealth address where funds are sent. */
  stealthAddress: Address;
  /** View tag for fast scanning (first byte of shared secret hash). */
  viewTag: Hex;
}

/** Result of scanning an announcement. */
export interface ScanResult {
  /** Whether this announcement is addressed to the scanner. */
  isMatch: boolean;
  /** The stealth address (if matched). */
  stealthAddress?: Address;
  /** The private key offset needed to spend from this stealth address. */
  stealthPrivKeyOffset?: Hex;
}

// ── Constants ─────────────────────────────────────────

/**
 * secp256k1 curve order.
 * All scalar arithmetic is done modulo this value.
 */
const SECP256K1_N = BigInt(
  "0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEBAAEDCE6AF48A03BBFD25E8CD0364141",
);

// ── Core Stealth Functions ────────────────────────────

/**
 * Generate a random ephemeral keypair for stealth address derivation.
 *
 * The private key is a cryptographically random 32-byte scalar.
 * The "public key" is its keccak hash (simplified; in production this
 * would be an EC point multiplication r·G on secp256k1).
 */
export function generateEphemeralKeyPair(): EphemeralKeyPair {
  const randomBytes = new Uint8Array(32);
  crypto.getRandomValues(randomBytes);

  const privateKey = `0x${Array.from(randomBytes)
    .map((b) => b.toString(16).padStart(2, "0"))
    .join("")}` as Hex;

  // Simplified: derive "public key" deterministically from private key.
  // A real implementation performs EC point multiplication (r·G).
  const publicKeyX = keccak256(
    encodePacked(["bytes32", "string"], [privateKey, "ephemeral-pub"]),
  );

  // Parity is deterministic from the hash of the full key
  const parityByte = parseInt(publicKeyX.slice(2, 4), 16);
  const parity = (parityByte % 2 === 0 ? 27 : 28) as number;

  return { privateKey, publicKeyX, parity };
}

/**
 * Compute the ECDH shared secret between an ephemeral key and a
 * recipient's view key.
 *
 * In a real implementation: `S = r · viewPubKey` (EC point multiplication).
 * Here we simulate using hash-based key agreement.
 */
export function computeSharedSecret(
  ephemeralPrivateKey: Hex,
  viewPubKeyX: Hex,
): Hex {
  return keccak256(
    encodePacked(["bytes32", "bytes32"], [ephemeralPrivateKey, viewPubKeyX]),
  );
}

/**
 * Derive a stealth address from the recipient's spend key and a shared secret.
 *
 * Protocol:
 *   offset = hash(sharedSecret) mod N
 *   stealthAddr = address(keccak256(spendPubKeyX || parity || offset))
 *
 * Matches the on-chain StealthAddress.deriveStealthAddress() logic.
 */
export function deriveStealthAddress(
  meta: StealthMetaAddress,
  sharedSecretHash: Hex,
): { stealthAddress: Address; offset: Hex } {
  const offsetBn = BigInt(sharedSecretHash) % SECP256K1_N;
  const offset = `0x${offsetBn.toString(16).padStart(64, "0")}` as Hex;

  const raw = keccak256(
    encodePacked(
      ["uint256", "uint8", "uint256"],
      [BigInt(meta.spendPubKeyX), meta.spendPubKeyParity, offsetBn],
    ),
  );

  // Take the last 20 bytes as the address
  const stealthAddress = getAddress(`0x${raw.slice(26)}`) as Address;

  return { stealthAddress, offset };
}

/**
 * Compute the view tag for fast announcement scanning.
 * The view tag is the first byte of hash(sharedSecret).
 * Recipients can discard ~99.6% of announcements without full ECDH.
 */
export function computeViewTag(sharedSecretHash: Hex): Hex {
  return `0x${sharedSecretHash.slice(2, 4)}` as Hex;
}

/**
 * Generate a stealth announcement to publish on-chain.
 *
 * Sender flow:
 *   1. Generate ephemeral keypair
 *   2. Compute shared secret with recipient's view key
 *   3. Derive stealth address from shared secret + spend key
 *   4. Compute view tag for fast scanning
 *   5. Return the announcement struct
 */
export function createStealthAnnouncement(recipientMeta: StealthMetaAddress): {
  announcement: StealthAnnouncement;
  ephemeralPrivateKey: Hex;
} {
  const ephemeral = generateEphemeralKeyPair();

  const sharedSecret = computeSharedSecret(
    ephemeral.privateKey,
    recipientMeta.viewPubKeyX,
  );

  const sharedSecretHash = keccak256(encodePacked(["bytes32"], [sharedSecret]));

  const { stealthAddress } = deriveStealthAddress(
    recipientMeta,
    sharedSecretHash,
  );

  const viewTag = computeViewTag(sharedSecretHash);

  return {
    announcement: {
      ephemeralPubKeyX: ephemeral.publicKeyX,
      ephemeralPubKeyParity: ephemeral.parity,
      stealthAddress,
      viewTag,
    },
    ephemeralPrivateKey: ephemeral.privateKey,
  };
}

/**
 * Scan a single announcement to determine if it's addressed to the scanner.
 *
 * Recipient flow:
 *   1. Compute shared secret S' = viewPrivKey · R (simulated with hash)
 *   2. Check view tag — skip if mismatch (~99.6% filtered)
 *   3. Derive expected stealth address from S' + spend key
 *   4. Compare with the announcement's stealth address
 */
export function scanAnnouncement(
  announcement: {
    ephemeralPubKeyX: Hex;
    stealthAddress: Address;
    viewTag: Hex;
  },
  viewPrivateKey: Hex,
  spendMeta: StealthMetaAddress,
): ScanResult {
  // Reconstruct shared secret from view private key + ephemeral public key
  const sharedSecret = computeSharedSecret(
    viewPrivateKey,
    announcement.ephemeralPubKeyX,
  );

  const sharedSecretHash = keccak256(encodePacked(["bytes32"], [sharedSecret]));

  // Fast check: view tag comparison
  const expectedViewTag = computeViewTag(sharedSecretHash);
  if (expectedViewTag !== announcement.viewTag) {
    return { isMatch: false };
  }

  // Full check: derive stealth address and compare
  const { stealthAddress, offset } = deriveStealthAddress(
    spendMeta,
    sharedSecretHash,
  );

  if (
    stealthAddress.toLowerCase() === announcement.stealthAddress.toLowerCase()
  ) {
    return {
      isMatch: true,
      stealthAddress,
      stealthPrivKeyOffset: offset,
    };
  }

  return { isMatch: false };
}

/**
 * Batch-scan multiple announcements.
 * Uses view tag filtering for ~256x speedup on average.
 *
 * @param announcements Array of on-chain announcements
 * @param viewPrivateKey Recipient's view private key
 * @param spendMeta Recipient's stealth meta-address
 * @returns Array of matched scan results
 */
export function scanAnnouncementBatch(
  announcements: Array<{
    ephemeralPubKeyX: Hex;
    stealthAddress: Address;
    viewTag: Hex;
  }>,
  viewPrivateKey: Hex,
  spendMeta: StealthMetaAddress,
): ScanResult[] {
  return announcements
    .map((a) => scanAnnouncement(a, viewPrivateKey, spendMeta))
    .filter((r) => r.isMatch);
}
